Interim checkin. Still not working properly: thread '<unnamed>' panicked at big_knn/src/big_knn_r_descent.rs:415:56: Illegal index of new_old_sims at 0,0 Shape is: [18, 0] new data shape = [18], old data shape = [0] ------- Still need to consider the sparsity of values in later merges.